######################## default configuration ####################
baseURL = "http://milsistemas.com"
languageCode = "en-us"
title = "Enov Hugo | Html5 Business template"
theme = "enov-hugo"
summaryLength = "10"
paginate = 4

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
######################### Plugins #############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themify/css/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/fontawesome/css/all.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/dist/magnific-popup.css"
  [[params.plugins.css]]
  URL = "plugins/slick-carousel/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/dist/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick-carousel/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/map.js"
  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3

  [[menu.main]]
  weight = 4
  name = "Pages"
  hasChildren = true

    [[menu.main]]
    parent = "Pages"
    name = "Portfolio"
    URL = "project"

    [[menu.main]]
    parent = "Pages"
    name = "Pricing"
    URL = "pricing"

    [[menu.main]]
    parent = "Pages"
    name = "Service"
    URL = "service"
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

  ################# footer menu ##################

  [[menu.footer1]]
  name = "service"
  URL = "service"
  weight = 1

  [[menu.footer1]]
  name = "about"
  URL = "about"
  weight = 2
  
  [[menu.footer1]]
  name = "blog"
  URL = "blog"
  weight = 3
  
  [[menu.footer1]]
  name = "pricing"
  URL = "pricing"
  weight = 4

  # footer menu 2
  [[menu.footer2]]
  name = "blog"
  URL = "blog"
  weight = 1

  [[menu.footer2]]
  name = "about"
  URL = "about"
  weight = 2
  
  [[menu.footer2]]
  name = "service"
  URL = "service"
  weight = 3
  
  [[menu.footer2]]
  name = "pricing"
  URL = "pricing"
  weight = 4

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
phone = "012548722120"
email = "example@email.com"
location = "290 Maryam Springs 260,Courbevoie, Paris, France"
copyright = "&copy; 2019 a theme by [themefisher](https://themefisher.com/)"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  # Navigation top header
  [params.topHeader]
  enable = true

  # Navigation button
  [params.navBtn]
  enable = true
  label = "Get a quote"
  link = "contact"

  #################### social icon ######################################
  [[params.social]]
  name = "Facebook"
  icon = "ti-facebook"
  link = "#"
  
  [[params.social]]
  name = "Twitter"
  icon = "ti-twitter-alt"
  link = "#"
  
  [[params.social]]
  name = "Vimeo"
  icon = "ti-vimeo-alt"
  link = "#"
  
  [[params.social]]
  name = "Github"
  icon = "ti-github"
  link = "#"
  
############################# post share links ######################
[[params.postShare]]
icon = "ti-facebook"
name = "facebook"
link = "#"

[[params.postShare]]
icon = "ti-twitter-alt"
name = "twitter"
link = "#"

[[params.postShare]]
icon = "ti-linkedin"
name = "linkedin"
link = "#"

[[params.postShare]]
icon = "ti-pinterest"
name = "pinterest"
link = "#"
